ALTER DATABASE OK2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG OK2 TO DISK = 'E:\Backup\DEVICE_OK2.bak' WITH INIT, NORECOVERY;
USE tempdb SET DATEFORMAT DMY
RESTORE DATABASE OK2 FROM  DEVICE_OK2 WITH FILE = 1, NORECOVERY;
RESTORE DATABASE OK2 FROM DISK = 'E:\Backup\DEVICE_OK2.bak'
WITH STOPAT='12/04/2022 11:05:00'
ALTER DATABASE  OK2 SET MULTI_USER 

--Test
ALTER DATABASE TEST3 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
USE tempdb

SELECT GETDATE()

BACKUP LOG TEST3 TO DISK = 'E:\Backup\DEVICE_TEST3.trn' WITH INIT, NORECOVERY 
USE TEMPDB
RESTORE DATABASE TEST3 FROM DEVICE_TEST3 WITH FILE = 1 , NORECOVERY

USE TEMPDB SET DATEFORMAT DMY
RESTORE DATABASE TEST3 FROM DISK = 'E:\Backup\DEVICE_TEST3.trn' 
WITH STOPAT = '14-04-2022 3:55:00 PM' , RECOVERY
ALTER DATABASE TEST3  SET MULTI_USER

--Nếu có lỗi
RESTORE DATABASE TEST3 FROM DEVICE_TEST3 WITH FILE= 2
ALTER DATABASE TEST3  SET MULTI_USER

--Xóa thông tin CSDL
USE msdb;  
GO  
EXEC sp_delete_database_backuphistory TEST5 



--Xóa 1 bản backup
EXEC master.sys.xp_delete_file 0 -- 0 cho tệp sao lưu hoặc 1 cho tệp báo cáo.
,'E:\Backup\DEVICE_TEST1.bak' -- Thư mục để xóa các tập tin. Đường dẫn phải kết thúc bằng dấu gạch chéo ngược
,'2022-04-14 10:47:30 AM' -- Ngày giới hạn cho những tệp cần được xóa.
, 1

--Xóa CSDL
DROP DATABASE TEST4